namespace Common.Networking.Packets.Enums;

public enum EClientOperationCode : ushort
{
//Socket
        ClientLogin = 0x1,
        SelectWorld = 0x4,
        CheckUserLimit = 0x5,
        WorldInfoRequest = 0x6,
        SelectCharacter = 0xB,
        PlayerMigration = 0xC,
        CheckDuplicatedID = 0xD,
        CreateNewCharacter = 0x11,
        DeleteCharacter = 0x14,
        ExceptionLog = 0x16,
        ClientStart = 0x1D,
        ClientValidation = 0x1F,
        //User
        UserTransferFieldRequest = 0x22,
        UserTransferChannelRequest = 0x23,
        UserMigrateToCashShopRequest = 0x24,
        UserMove = 0x25,
        UserSitRequest,
        UserPortableChairSitRequest,
        UserMeleeAttack = 0x29,
        UserShootAttack,
        UserMagicAttack,
        UserBodyAttack,
        UserMovingShootAttackPrepare,
        UserHit,
        UserAttackUser,
        UserChat,
        UserADBoardClose,
        UserEmotion,
        UserActivateEffectItem,
        UserUpgradeTombEffect,
        UserHP,
        Premium,
        UserBanMapByMob,
        UserMonsterBookSetCover,
        UserSelectNpc,
        UserRemoteShopOpenRequest,
        UserScriptMessageAnswer,
        UserShopRequest,
        UserTrunkRequest,
        UserEntrustedShopRequest,
        UserStoreBankRequest,
        UserParcelRequest,
        UserEffectLocal,
        ShopScannerRequest,
        ShopLinkRequest,
        AdminShopRequest,
        UserGatherItemRequest,
        UserSortItemRequest = 0x46,
        UserChangeSlotPositionRequest = 0x48,
        UserStatChangeItemUseRequest,
        UserStatChangeItemCancelRequest,
        UserStatChangeByPortableChairRequest,
        UserMobSummonItemUseRequest,
        UserPetFoodItemUseRequest,
        UserTamingMobFoodItemUseRequest,
        UserScriptItemUseRequest,
        UserConsumeCashItemUseRequest,
        UserDestroyPetItemRequest,
        UserBridleItemUseRequest,
        UserSkillLearnItemUseRequest,
        UserSkillResetItemUseRequest,
        UserShopScannerItemUseRequest,
        UserMapTransferItemUseRequest,
        UserPortalScrollUseRequest,
        UserUpgradeItemUseRequest,
        UserHyperUpgradeItemUseRequest,
        UserItemOptionUpgradeItemUseRequest,
        UserUIOpenItemUseRequest,
        UserItemReleaseRequest,
        UserAbilityUpRequest,
        UserAbilityMassUpRequest,
        UserChangeStatRequest,
        UserChangeStatRequestByItemOption,
        UserSkillUpRequest,
        UserSkillUseRequest,
        UserSkillCancelRequest,
        UserSkillPrepareRequest,
        UserDropMoneyRequest,
        UserGivePopularityRequest,
        UserPartyRequest,
        UserCharacterInfoRequest,
        UserActivatePetRequest,
        UserTemporaryStatUpdateRequest,
        UserPortalScriptRequest,
        UserPortalTeleportRequest,
        UserMapTransferRequest,
        UserAntiMacroItemUseRequest,
        UserAntiMacroSkillUseRequest,
        UserAntiMacroQuestionResult,
        UserClaimRequest,
        UserQuestRequest,
        UserCalcDamageStatSetRequest,
        UserThrowGrenade,
        UserMacroSysDataModified,
        UserSelectNpcItemUseRequest,
        UserLotteryItemUseRequest,
        UserItemMakeRequest,
        UserSueCharacterRequest,
        UserUseGachaponBoxRequest,
        UserUseGachaponRemoteRequest,
        UserUseWaterOfLife,
        UserRepairDurabilityAll,
        UserRepairDurability,
        UserQuestRecordSetState,
        UserClientTimerEndRequest,
        UserFollowCharacterRequest,
        UserFollowCharacterWithdraw,
        UserSelectPQReward,
        UserRequestPQReward,
        SetPassenserResult,
        BroadcastMsg,
        GroupMessage,
        Whisper,
        CoupleMessage,
        Messenger,
        MiniRoom,
        PartyRequest,
        PartyResult,
        ExpeditionRequest,
        PartyAdverRequest,
        GuildRequest,
        GuildResult,
        Admin,
        Log,
        FriendRequest,
        MemoRequest,
        MemoFlagRequest,
        EnterTownPortalRequest,
        EnterOpenGateRequest,
        SlideRequest,
        FuncKeyMappedModified,
        RPSGame,
        MarriageRequest,
        WeddingWishListRequest,
        WeddingProgress,
        GuestBless,
        BoobyTrapAlert,
        StalkBegin,
        AllianceRequest,
        AllianceResult,
        FamilyChartRequest,
        FamilyInfoRequest,
        FamilyRegisterJunior,
        FamilyUnregisterJunior,
        FamilyUnregisterParent,
        FamilyJoinResult,
        FamilyUsePrivilege,
        FamilySetPrecept,
        FamilySummonResult,
        ChatBlockUserReq,
        GuildBBS,
        UserMigrateToITCRequest,
        UserExpUpItemUseRequest,
        UserTempExpUseRequest,
        NewYearCardRequest,
        RandomMorphRequest,
        CashItemGachaponRequest,
        CashGachaponOpenRequest,
        ChangeMaplePointRequest,
        TalkToTutor,
        RequestIncCombo,
        MobCrcKeyChangedReply,
        RequestSessionValue,
        UpdateGMBoard,
        AccountMoreInfo,
        FindFriend,
        AcceptAPSPEvent,
        UserDragonBallBoxRequest,
        UserDragonBallSummonRequest,
        //Pet
        PetMove,
        PetAction,
        PetInteractionRequest,
        PetDropPickUpRequest,
        PetStatChangeItemUseRequest,
        PetUpdateExceptionListRequest,
        //Summoned
        SummonedMove,
        SummonedAttack,
        SummonedHit,
        SummonedSkill,
        Remove,
        //Dragon
        DragonMove = 0xD0,
        //
        QuickslotKeyMappedModified,
        PassiveskillInfoUpdate,
        UpdateScreenSetting,
        UserAttackUser_Specific,
        UserPamsSongUseRequest,
        QuestGuideRequest,
        UserRepeatEffectRemove,
        //Field
        //Life Pool
        //Mob
        MobMove = 0xDC,
        MobApplyCtrl,
        MobDropPickUpRequest,
        MobHitByObstacle,
        MobHitByMob,
        MobSelfDestruct,
        MobAttackMob,
        MobSkillDelayEnd,
        MobTimeBombEnd,
        MobEscortCollision,
        MobRequestEscortInfo,
        MobEscortStopEndRequest,
        //NPC
        NpcMove,
        NpcSpecialAction,
        //Drop Pool
        DropPickUpRequest,
        //Reactor Pool
        ReactorHit,
        ReactorTouch,
        RequireFieldObstacleStatus,
        //Event Field
        EventStart,
        SnowBallHit,
        SnowBallTouch,
        CoconutHit,
        TournamentMatchTable,
        PulleyHit,
        //Monster Carnival Field
        MCarnivalRequest,
        //
        CONTISTATE,
        //Party Match
        InvitePartyMatch,
        CancelInvitePartyMatch,
        //
        RequestFootHoldInfo,
        FootHoldInfo,
        //Cash Shop
        CashShopChargeParamRequest,
        CashShopQueryCashRequest,
        CashShopCashItemRequest,
        CashShopCheckCouponRequest,
        CashShopGiftMateInfoRequest,
        //
        CheckSSN2OnCreateNewCharacter,
        CheckSPWOnCreateNewCharacter,
        FirstSSNOnCreateNewCharacter,
        //Raise
        RaiseRefesh,
        RaiseUIState,
        RaiseIncExp,
        RaiseAddPiece,
        //
        SendMateMail,
        RequestGuildBoardAuthKey,
        RequestConsultAuthKey,
        RequestClassCompetitionAuthKey,
        RequestWebBoardAuthKey,
        //Item Upgrade
        GoldHammerRequest,
        GoldHammerComplete,
        //Battle Record
        BattleRecordOnOffRequest,
        //Maple TV
        MapleTVSendMessageRequest,
        MapleTVUpdateViewCount,
        //ITC
        ITCChargeParamRequest,
        ITCQueryCashRequest,
        ITCItemRequest,
        //Character Sale
        CheckDuplicatedIDInCS,
        //
        LogoutGiftSelect
}